### ISSUE TITLE
HOK Power BI Dashboards for Unreal

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3D-Repo-Product-Team#41]
### Description
HOK Power BI dashboards for Unreal video. Recording in 4K showing how BIM Data is extracted from 3D Repo.

### Sub-tasks
- [x] Find Dashboards
- [x] Tidy Up
- [x] Send dashboards to Matt

**Comment by BDavydov** [comment]
@mosment3DRepo Just let me know what Aspect Ration or px width x height these dashboards need to be. Thanks

**Comment by mosment3DRepo** [comment]
@BDavydov 16x9 is good, Resolution shouln't matter as it's all vectors in PowerBI anyway

**Comment by BDavydov** [comment]
@mosment3DRepo [Power BI Dashboard](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/HOK/Projects%20and%20data/CENTRUS/Power%20BI)
